[tool.mypy]
strict = true
no_implicit_optional = true
strict_optional = true
warn_no_return = true
warn_unreachable = true
warn_incomplete_stub = true

pretty = true
show_error_context = true
show_column_numbers = true
show_error_codes = true
show_error_code_links = true
show_traceback = true

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100
include_trailing_comma = true
